version: '3.8'

services:
  vitejs-app:
    container_name: vitejs-app
    image: dakeinu/curriculum:latest
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - vitejs-app
    networks:
      - webnet
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: sh -c 'while :; do sleep 12h & wait $${!}; certbot renew; done;'
    command:
      [
        'certonly',
        '--webroot',
        '--webroot-path=/var/www/certbot',
        '--email rfalcati@gmail.com',
        '--agree-tos',
        '--no-eff-email',
        '-d falcatiremi.com',
        '--non-interactive'
      ]
    depends_on:
      - nginx
    networks:
      - webnet
    restart: unless-stopped

networks:
  webnet:
