version: '3.8'

services:
  vitejs-app:
    container_name: remif-curriculum
    image: dakeinu/curriculum 
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet: